[package]
name = "peekaboo"
version = "0.1.0"
authors = ["Chua Zheng Leong <czl@iiyume.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
